apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki.js
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pipol31/wikijs
    path: chart/wiki.js
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wiki.js
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
